### ISSUE TITLE
2020 tower spring cleaning

### ISSUE THREAD

**Issue by jonhoo** [tower-rs/tower#431]
It's about time we made a serious push to make `tower` "ready for public use". Here is a list of what should happen to make that a reality:

 - [x] Merge all middleware crates (everything except `tower-service`) into a single `tower` crate like [tokio did](https://github.com/tokio-rs/tokio/issues/1318). We should add features that enable and disable different middleware, with all features being [off by default](https://github.com/tokio-rs/tokio/issues/1791).
 - [x] Unify the error bounds across all middleware to all use either `From` or `Into` (see https://github.com/tower-rs/tower/issues/387). We should also think about https://github.com/rust-lang/api-guidelines/pull/210, and whether we want to stop printing the source when we print our errors.
 - [x] Make a decision on how to move forward with `poll_ready` (see https://github.com/tower-rs/tower/issues/408, https://github.com/tower-rs/tower/issues/412, and https://github.com/rust-lang/futures-rs/issues/2109).
 - [x] Update CI to match new crate org, and include basic amenities (like [`cargo-deny`](https://github.com/tower-rs/tower/issues/403)).
 - [ ] Update _all_ docs to at least have all items documented (`#![deny(missing_docs)]`) and basic usage examples + module docs. We should also tidy up the `README` + crate docs + metadata while we're at it. See also https://github.com/tower-rs/tower/issues/33.
 - [x] Update all code with [`doc_cfg`](https://doc.rust-lang.org/unstable-book/language-features/doc-cfg.html) when running on docs.rs (see https://github.com/tokio-rs/tokio/pull/1808), and enable all features on docs.rs (like https://github.com/tokio-rs/tokio/pull/1471)
 - [x] Figure out how to manage modules that previously had `publish = false`. We could make them non-`pub`, though that would make the tests stop working...
 - [ ] Add free function shorthands for some of the various modules (à la warp), such as `tower::balance::p2c::layer()` or `tower::balance::p2c()` as a shorthand for `tower::balance::p2c::MakeBalanceLayer::new()`.
 - [x] Consider if `Target` should be renamed to a more understandable name. Perhaps `Endpoint`?

For the per-crate/module docs cleanup, here are the things we need to do, what we have done, and who's going to do each one. If you want to make a pass over one of these, please post here to claim so we don't duplicate the work. As you make your pass, please also create issues for implementation and API issues you spot (for example, `limit` should probably not [vendor parts of `tokio::sync`](https://github.com/tower-rs/tower/tree/master/tower-limit/src/concurrency/sync)).

 - [ ] `tower-layer`
 - [ ] `tower-service`
 - [ ] `tower-test` (@jonhoo)
 - [ ] `tower` itself
   - [x] `tower/balance` (https://github.com/tower-rs/tower/pull/449)
   - [x] `tower/buffer` (https://github.com/tower-rs/tower/pull/444)
   - [ ] `tower/builder`
   - [x] `tower/discover` (https://github.com/tower-rs/tower/pull/443)
   - [ ] `tower/filter`
   - [ ] `tower/hedge`
   - [ ] `tower/limit`
   - [x] `tower/load` (https://github.com/tower-rs/tower/pull/445)
   - [ ] `tower/load_shed`
   - [ ] `tower/make`
   - [ ] `tower/ready_cache`
   - [ ] `tower/reconnect`
   - [ ] `tower/retry`
   - [ ] `tower/spawn_ready`
   - [ ] `tower/steer`
   - [ ] `tower/timeout`
   - [ ] `tower/util`

Things we would also like to do, but are not blockers:

 - [x] Create more GitHub issue labels, especially one for each module.
 - [x] Triage all GitHub issues, apply appropriate labels, close stale issues.
 - [x] Triage all current GitHub PRs, and make steps to move each one forward (may just consist of pinging the author).

**Comment by hawkw** [comment]
>     * Update _all_ docs to at least have all items documented (`#![deny(missing_docs)]`) and basic usage examples + module docs. We should also tidy up the `README` + crate docs + metadata while we're at it. See also #33.

We should probably also add the `doc_cfg` nightly feature to docs.rs builds, and add the appropriate attributes to feature-flagged APIs (similar to tonic, tokio, etc).

**Comment by jonhoo** [comment]
I've updated the `v0.3.x` branch to point to the current head of `master` (0f9eb648a5654bfe4f95c008074aac28fd6fc80c). Going forward, `master` will be where we develop the "new and shiny", and then any maintenance of the `0.3` releases will happen on `v0.3.x`. The thinking is that this will incentivize us to get a new `tower` release out as soon as we can, to minimize the time that there is a mismatch between `master` and the code that people get through crates.io.

**Comment by jonhoo** [comment]
We now have [tons of fancy new labels](https://github.com/tower-rs/tower/labels?sort=name-asc).

**Comment by davidbarsky** [comment]
@jonhoo A few notes on `poll_ready`:
- I think Tower should move to the model with an explicit semaphore, but I'm not sure this requires a new associated type. 
- I'd also like to see a corresponding high-level trait (called `Dispatch`, maybe? Bikesheds welcome) which _does not_ expose a public `poll_ready` method and changes the `call` method to take `&self` introduced alongside the new `Service` trait, as `Service` is getting more and more low-level.
- If `tower::Service` moves to a semaphore-based approach, is there any value in keeping `&mut self` around? Tokens + `&self` could reduce how many `.clone()s` need to be written.

**Comment by jonhoo** [comment]
I did triage!

**Comment by jonhoo** [comment]
@davidbarsky Can you say more about what you mean by "explicit semaphore". Are you thinking about #412, or something else? Also, I'm not sure I follow why `Dispatch` would be useful?

**Comment by jonhoo** [comment]
Also, I wonder if we should keep the discussion of `poll_ready` to #408. Or maybe we (you? :p) should make a new meta-issue specifically about `poll_ready`? And then arguably close #408 and #412, since they are both _specific_ proposals, both of which can be folded into one bigger discussion around `poll_ready`.

**Comment by davidbarsky** [comment]
@jonhoo Yeah, some sort of dedicated issue for `poll_ready` is a good idea. I'll create one later today once I clear this morning's round of meetings.

@hawkw 

> This sounds a lot like the ReadyService trait that was added in #25 and then removed in #50. IIRC, there were some issues with ReadyService that lead to its removal. We should probably do some thinking about whether those issues still apply before reintroducing a similar trait.

Ah, good to know. I'll take a look at that those two issues.

> What do you mean by "explicit semaphore"? If you're proposing adding a semaphore-based concurrency control mechanism to every service, I'm not sure how I feel about that. Many services (including most middleware services) don't require their own concurrency control, just propagating backpressure from lower-level services up the stack. Am I understanding what you mean correctly?

By "explicit semaphore", I was referring to the proposal outlined in https://github.com/tower-rs/tower/issues/412. Backpressure would be propagated by passing a token up through the Service stack rather than relying on each `Service` to call `poll_ready()` themselves. That being said, the Lock approach you mentioned that exists in Linkerd might be a compelling alternative.

**Comment by jonhoo** [comment]
(@davidbarsky see also https://github.com/rust-lang/futures-rs/issues/2109, which is my primary consideration for `poll_ready`)

**Comment by jonhoo** [comment]
Fixed the docs feature annotations and `publish = false` in https://github.com/tower-rs/tower/pull/442.

**Comment by hawkw** [comment]
Now that 0.4 has been shipped, I think we can call this "done"!
